-- Core schema for "Мама, дешевле!"
-- Creates the tables and functions referenced by the jobs but missing from the repo.
-- Safe to re-run (idempotent). Apply with Supabase migrations / `supabase db push`.

create extension if not exists pgcrypto;

-- ---------------------------------------------------------------------------
-- products: one row per discovered product, deduplicated by (source, external_id)
-- ---------------------------------------------------------------------------
create table if not exists public.products (
  id           uuid primary key default gen_random_uuid(),
  external_id  text not null,
  source       text not null,
  url          text not null,
  title        text not null,
  brand        text,
  category     text,
  age_label    text,
  image_url    text,
  rating       numeric,
  reviews_count integer,
  available    boolean not null default true,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now(),
  unique (source, external_id)
);

create index if not exists products_source_external_idx on public.products (source, external_id);
create index if not exists products_available_idx on public.products (available);

-- ---------------------------------------------------------------------------
-- prices: immutable history of price snapshots per product
-- ---------------------------------------------------------------------------
create table if not exists public.prices (
  id           bigint generated by default as identity primary key,
  product_id   uuid not null references public.products (id) on delete cascade,
  price        numeric not null,
  old_price    numeric,
  collected_at timestamptz not null default now()
);

create index if not exists prices_product_collected_idx on public.prices (product_id, collected_at desc);

-- ---------------------------------------------------------------------------
-- deals: a computed deal candidate/suggestion for a product
-- ---------------------------------------------------------------------------
create table if not exists public.deals (
  id                 uuid primary key default gen_random_uuid(),
  product_id         uuid not null references public.products (id) on delete cascade,
  current_price      numeric not null,
  reference_price    numeric not null,
  discount_percent   numeric not null,
  deal_score         integer not null,
  deal_level         text not null,
  ai_reason          text,
  status             text not null default 'candidate',
  created_at         timestamptz not null default now(),
  published_at       timestamptz
);

create index if not exists deals_status_score_idx on public.deals (status, deal_score desc);
create index if not exists deals_product_idx on public.deals (product_id);

-- ---------------------------------------------------------------------------
-- telegram_posts: record of every published Telegram post (de-dupes publishing)
-- ---------------------------------------------------------------------------
create table if not exists public.telegram_posts (
  id                 uuid primary key default gen_random_uuid(),
  deal_id            uuid not null references public.deals (id) on delete cascade,
  telegram_message_id bigint not null,
  published_price    numeric not null,
  post_text          text,
  published_at       timestamptz not null default now()
);

create index if not exists telegram_posts_deal_idx on public.telegram_posts (deal_id);

-- ---------------------------------------------------------------------------
-- telegram_price_alerts: per-user price watches on a product
-- ---------------------------------------------------------------------------
create table if not exists public.telegram_price_alerts (
  id               uuid primary key default gen_random_uuid(),
  telegram_user_id bigint not null,
  chat_id          bigint not null,
  product_id       uuid not null references public.products (id) on delete cascade,
  target_price     numeric,
  active           boolean not null default true,
  notified_price   numeric,
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now(),
  unique (telegram_user_id, product_id)
);

create index if not exists telegram_price_alerts_product_idx on public.telegram_price_alerts (product_id);
create index if not exists telegram_price_alerts_active_idx on public.telegram_price_alerts (active);

-- ---------------------------------------------------------------------------
-- telegram_conversation_messages: chat memory for the conversation agent
-- ---------------------------------------------------------------------------
create table if not exists public.telegram_conversation_messages (
  id               uuid primary key default gen_random_uuid(),
  telegram_user_id bigint not null,
  role             text not null check (role in ('user', 'assistant')),
  message_text     text,
  created_at       timestamptz not null default now()
);

create index if not exists telegram_conversation_user_idx on public.telegram_conversation_messages (telegram_user_id, created_at desc);

-- ---------------------------------------------------------------------------
-- telegram_bot_lock: single-row advisory lock so only one bot worker runs
-- ---------------------------------------------------------------------------
create table if not exists public.telegram_bot_lock (
  id          int primary key default 1,
  owner_token text,
  locked_at   timestamptz
);

insert into public.telegram_bot_lock (id) values (1) on conflict (id) do nothing;

create or replace function public.acquire_telegram_bot_lock(p_owner_token text, p_stale_minutes int)
returns boolean
language plpgsql
as $$
declare
  v_owner text;
  v_locked_at timestamptz;
begin
  select owner_token, locked_at into v_owner, v_locked_at
  from public.telegram_bot_lock where id = 1 for update;

  if v_owner is null or v_owner = p_owner_token
     or (v_locked_at is not null and v_locked_at < now() - (p_stale_minutes || ' minutes')::interval) then
    update public.telegram_bot_lock set owner_token = p_owner_token, locked_at = now() where id = 1;
    return true;
  end if;
  return false;
end;
$$;

create or replace function public.refresh_telegram_bot_lock(p_owner_token text)
returns boolean
language plpgsql
as $$
declare
  v_owner text;
begin
  select owner_token into v_owner from public.telegram_bot_lock where id = 1 for update;
  if v_owner = p_owner_token then
    update public.telegram_bot_lock set locked_at = now() where id = 1;
    return true;
  end if;
  return false;
end;
$$;

create or replace function public.release_telegram_bot_lock(p_owner_token text)
returns boolean
language plpgsql
as $$
declare
  v_owner text;
begin
  select owner_token into v_owner from public.telegram_bot_lock where id = 1 for update;
  if v_owner = p_owner_token then
    update public.telegram_bot_lock set owner_token = null, locked_at = null where id = 1;
    return true;
  end if;
  return false;
end;
$$;

-- Row Level Security: service role (used by jobs) bypasses RLS; lock the tables down.
alter table public.products enable row level security;
alter table public.prices enable row level security;
alter table public.deals enable row level security;
alter table public.telegram_posts enable row level security;
alter table public.telegram_price_alerts enable row level security;
alter table public.telegram_conversation_messages enable row level security;
alter table public.telegram_bot_lock enable row level security;
