create table if not exists public.search_requests (
  id bigint generated by default as identity primary key,
  telegram_user_id bigint not null,
  chat_id bigint not null,
  query_text text not null,
  created_at timestamptz not null default now()
);

create index if not exists search_requests_user_created_idx
  on public.search_requests (telegram_user_id, created_at desc);

alter table public.search_requests enable row level security;
