-- Click analytics for affiliate/tracked links.
create table if not exists public.link_clicks (
  id          bigint generated by default as identity primary key,
  product_id  uuid not null references public.products (id) on delete cascade,
  source      text,
  created_at  timestamptz not null default now()
);

create index if not exists link_clicks_product_idx on public.link_clicks (product_id);
create index if not exists link_clicks_created_idx on public.link_clicks (created_at desc);

alter table public.link_clicks enable row level security;
